### ISSUE TITLE
Assertion failed @ propagator.h:68

### ISSUE THREAD

**Issue by rtaupe** [chuffed/chuffed#1]
Hi,

I successfully compiled chuffed myself on Windows.
However, on the OOCSP instance [oocsp_racks_030_e6_cc](https://github.com/geoffchu/chuffed/files/594201/oocsp_racks_030_e6_cc.zip) of this year´s [MiniZinc Challenge](http://www.minizinc.org/challenge2016/results2016.html), I get the following output:

> D:\repos\chuffed\chuffed/core/propagator.h:68: Assertion failed.

See also [here](https://github.com/geoffchu/chuffed/issues/10) for a similar issue.

Hope you can help.

Thanks,
Richard

**Comment by rtaupe** [comment]
The error does not occur when I compile on Ubuntu.

**Comment by schutta** [comment]
Does the same happen if Chuffed is compiled in non-parallel version?

**Comment by rtaupe** [comment]
How do you compile Chuffed in non-parallel version? Can't find anything in [README.md](../blob/master/README.md).

**Comment by schutta** [comment]
The steps given in the README.md are for the non-parallel version if you leave the file CMakeLists.txt unchanged.

**Comment by rtaupe** [comment]
I have left CMakeLists.txt unchanged, so yes, the bug occurs in the non-parallel version.

**Comment by schutta** [comment]
I am not able to recreate the issue.

Can you provide me the following details, please?

- Used Chuffed's version (branch: master, develop) and commit
- Used CMake compilation steps
- Used MiniZinc version and used compilation command to flatten the model
- Used "fzn-chuffed" execution command and approximate time until the error message is thrown

**Comment by schutta** [comment]
Does the issue happen with the latest [develop](https://github.com/chuffed/chuffed/tree/develop) version commit 1a8ddb3?

**Comment by rtaupe** [comment]
> Used Chuffed's version (branch: master, develop) and commit

master da05326ca3faa251e491e9403ef9e3d6f6310535

> Used CMake compilation steps

[cmake.log](https://github.com/chuffed/chuffed/files/1514180/cmake.log)
[cmake_build.log](https://github.com/chuffed/chuffed/files/1514179/cmake_build.log)

> Used MiniZinc version and used compilation command to flatten the model

MiniZinc to FlatZinc converter, version 2.1.6
`$ mzn2fzn -G chuffed -o oocsp_racks_030_e6_cc.fzn oocsp_racks.mzn oocsp_racks_030_e6_cc.dzn`

> Used "fzn-chuffed" execution command and approximate time until the error message is thrown

`$ .Debug/fzn-chuffed.exe oocsp_racks_030_e6_cc.fzn`
After about 45 seconds the following dialog pops up.
![error_master](https://user-images.githubusercontent.com/1563953/33380965-02166966-d51d-11e7-97b5-255d1d9f1b2e.png)
When I press "Abort" or "Ignore", the error message "D:\repos\chuffed\chuffed/core/propagator.h:68: Assertion failed." is printed to stderr. When I press "Continue", the program just silently terminates.

> BTW: Does the issue happen with the latest develop version commit 1a8ddb34f8789624153868c29a054d3b9b6ae362?

Here I get a different popup:
![error_develop](https://user-images.githubusercontent.com/1563953/33380978-0a3d80fc-d51d-11e7-9bc4-69c2617c6584.png)
Then, the program silently terminates no matter which button I press.

**Comment by kletzi** [comment]
I ran into the same issues trying to compile chuffed on Windows.

However, I could find a working configuration, using the 64-bit generator for cmake and compiling the Release version which works differently that described in the readme when using Visual Studio:

`cmake -G "Visual Studio 15 2017 Win64" ..`
`cmake --build . --config Release`

**Comment by Dekker1** [comment]
This issue seems stale, and I will close it for now. If this or a similar issue is found again, a new issue can be created.
