### ISSUE TITLE
The new Chuffed is slower than before

### ISSUE THREAD

**Issue by o-fir** [chuffed/chuffed#109]
After running multiple tests, I have remarked that the solver is consistently slower after the latest update.
 
Take a look at the performance of the two versions on a couple of benchmarks:
![Figure_1](https://user-images.githubusercontent.com/99724660/220868663-cc450306-f9dd-402a-9da3-ae872fa8d36b.png)
![Figure_2](https://user-images.githubusercontent.com/99724660/220868671-05e653ff-efcb-4be3-94d1-3ee3a6b29781.png)
![Figure_3](https://user-images.githubusercontent.com/99724660/220868669-95fd07b2-9509-4655-9791-c5fafa6b00bb.png)

It may be "cheaper" to run on domains without holes, rather than have Chuffed support them - I will change the modelisation of the problems and try to see if it's true

**Comment by Dekker1** [comment]
This does indeed seem a little concerning, so it would probably be best to investigate further.

First it is important to know what versions of Chuffed you are comparing. Are you comparing the last two releases, or just Chuffed with and without the fix to the bug you previously reported? (If you would post the commits you are compiling, then that would be helpful). To actually do some runtime comparisons I will also need some of the instance files that show a significant difference (preferably with different runtimes).

Just as a check, you did make sure you compiled the two versions of chuffed with the same optimisation flags? (CMake's "Release" profile?)

**Comment by schutta** [comment]
There can be different reasons why Chuffed is slower on your benchmarks ranging from bug fixes over new features or a different search was performed. To investigate further the best would be that you share your benchmark models and instances. If you can do it then please re-run the benchmarks, provide us the full statistic information for each run, a list of constraints in your benchmarks, and what @Dekker1 mentioned in his comment.
