### ISSUE TITLE
Incorrect unsatisfiability

### ISSUE THREAD

**Issue by anonymous192837** [chuffed/chuffed#118]
I have a FlatZinc model that is incorrectly considered unsatisfiable. The model works correctly after changing these cases of `getLit(i, 1)` to `getLit(i, 0)`:

https://github.com/chuffed/chuffed/blob/3c3a8d9c381033c335ec821f6354e283f1fc9ca9/chuffed/primitives/element.cpp#L513
https://github.com/chuffed/chuffed/blob/3c3a8d9c381033c335ec821f6354e283f1fc9ca9/chuffed/primitives/element.cpp#L547

That is, a clause should probably contain `x != i` rather than `x = i` if i is not in the domain of x.

Also, the `no_max_support` branch uses `INT_MIN`, as opposed to `INT64_MIN` for `no_min_support`, but this doesn't make a difference.

There is similar code here, for which this may also apply:

https://github.com/chuffed/chuffed/blob/3c3a8d9c381033c335ec821f6354e283f1fc9ca9/chuffed/primitives/element.cpp#L308
https://github.com/chuffed/chuffed/blob/3c3a8d9c381033c335ec821f6354e283f1fc9ca9/chuffed/primitives/element.cpp#L353

**Comment by guidotack** [comment]
I'm not sure your proposed fix is correct. Consider an example where `x in {1,3,5}`, and we have an array `a` and the result variable `y`. Then the clause we need to generate as the explanation for `y >= new_m` is

```
y >= new_m \/ a[1] < new_m \/ x=2 \/ a[3] < new_m \/ x=4 \/ a[5] < new_m
```

Which is exactly what the code seems to do. By replacing the `x=i` with `x!=i`, you're essentially just disabling the clause, since it will be trivially true most of the time. That's probably masking some other bug somewhere if the model is indeed satisfiable.

Could you send us the model, so that we can have a look at the bug in more detail?

**Comment by anonymous192837** [comment]
You're correct, I misinterpreted a clause as a conjunction `a /\ b /\ c /\ ... -> false`. I'll try to simplify the model into something shareable.

**Comment by anonymous192837** [comment]
I built with the lastest develop branch, but the issue does not occur anymore. I only found one related change, and was just curious whether this is intentional (i.e., the swap of LE/GE)?

https://github.com/chuffed/chuffed/commit/8e083f4d42323216373636a1abdff634866248fa#diff-611c51905d60923ac49fa84d8b23a7c9922b996e1da9e9d93a58af9754f0e16cR129-R132

**Comment by Dekker1** [comment]
This is indeed a mistake, thank you for catching that. I tried to make as make replacements automatically to avoid these mistakes, but it seems from the 4 places that I had to do manually, these 2 where wrong. I will fix the mistake shortly.

If this was the change that solved your problem, then this would indicate that the rounding to the nearest number (in `transform`) has some mistake.

**Comment by anonymous192837** [comment]
I've attached a FlatZinc model for which this issue occurs. I'm aware that it is quite large. The model can be made satisfiable by uncommenting the last constraint.

[test.txt](https://github.com/chuffed/chuffed/files/11288066/test.txt)

Edit: here's a smaller model: [test.txt](https://github.com/chuffed/chuffed/files/11301418/test.txt)

**Comment by Dekker1** [comment]
Thank you for the smaller example, I'm having a look now to see whether I can find where things go wrong.

**Comment by Dekker1** [comment]
I've localized the problem to be in the `IntVarSL` class, for sparse domain variables. Only `X_INTRODUCED_8_` is created as such a variable, but when creating an eager literal instead, it has the correct behaviour. 

So far the inconsistencies I've found, have only been in the debug printing, so I'm still trying to find where something goes wrong.
