### ISSUE TITLE
Unexpected unsatisfiability using lex_less

### ISSUE THREAD

**Issue by Dekker1** [chuffed/chuffed#127]
As reported in #116
```
include "globals.mzn";
var 1..1 union 4..4: A;
var 1..3: B;
var 2..3: C;
var 1..4: D;
var 1..1 union 3..4: E;
constraint
  lex_less([E,A,3],[3,4,3]);
constraint
  lex_less([3,4,3],[C,D,B]);
solve :: int_search([A,B,C,D,E], anti_first_fail, indomain_interval, complete) satisfy;
```

**Comment by Dekker1** [comment]
Looking further into this issue, I found that this model is is actually correctly declared unsatisfiable. In the second `lex_less` constraint, the maximum values that the variables in the array literal `[C,D,B]` can take are `[3,4,3]`, but since these are the same values this is not strictly less than the array as the first argument. The MUS is thus:

```
include "lex_less.mzn";
var 1..3: B;
var 2..3: C;
var 1..4: D;
constraint lex_less([3,4,3],[C,D,B]);
```

The inconsistency seems to even be detected during MiniZinc compilation. I don't think there is any bug here. @matsc-at-sics-se Please let me know if I overlooked anything, and I'll reopen the issue.

**Comment by matsc-at-sics-se** [comment]
Of course, that's sloppy of me.  But the following model gives two solutions, both wrong. 
On closer examination, the bug seems to be in `minizinc` 2.7.2 (the flattener).
So, Chuffed is in the clear on this one!
```
include "globals.mzn";
var 1..2: A;
var 1..2: B;
constraint lex_less([2,B,2],[A,1,2]);
```
