### ISSUE TITLE
Using Minizinc option -t kills Chuffed before it prints output

### ISSUE THREAD

**Issue by raphaelboudreault** [chuffed/chuffed#135]
Relates to https://github.com/chuffed/chuffed/issues/85 and https://github.com/MiniZinc/libminizinc/issues/523.

While I thought that MR https://github.com/chuffed/chuffed/pull/87 and https://github.com/chuffed/chuffed/pull/88 would solve this issue, it still happens on Windows 10 using MiniZinc 2.7.2. The flag -t is now passed correctly to Chuffed, but it seems like MiniZinc still kills Chuffed before it has the time to print anything. This can be seen using the flag -s, where Chuffed doesn't print any of its statistics when the timeout kicks in (when I'm pretty sure back in the days, it was doing so). Note that this behavior of missing output also happens when using Ctrl+C (only \*\*\*Interrupted\*\*\* is printed).

**Comment by Dekker1** [comment]
We believe that the problem was caused by Chuffed not printing the comment that terminates a statistics block. This meant that MiniZinc did not flush the statistics back to the user.
