### ISSUE TITLE
Solving always stops at the first restart when not using the new on_restart features

### ISSUE THREAD

**Issue by Samclou** [chuffed/chuffed#149]
I don't know if it is actually an issue but on the present commit (f1dda4f), when the new on_restart features from fde2fbc are not used, solving seems to always stop at the first restart. 

For exemple, for a simple optimisation problem such as [simple_opt.txt](https://github.com/chuffed/chuffed/files/11882905/simple_opt.txt), the solver stops after finding a first solution (a=b=1) and incorrectly reports it as optimal.

For a more convoluted satisfaction problem such as [weird_sat.txt](https://github.com/chuffed/chuffed/files/11883110/weird_sat.txt), using the free search option, the solver rapidly reports it as unsatisfiable even thought it has a solution (a[i]=b[i]=i, \forall i \in 0..100 and c being a one-hot vector). 

The cause seems to be that when the on_restart features are not used, the `enable_on_restart` attribute of `FlatZincSpace` is 
always false, meaning that the method `onRestart` always immediately returns true, killing the search either at line 380, 883, 910, or 948 of the file engine.cpp. Perhaps the line 698 of the file flatzinc.cpp `return true;` should be replaced by the line `return false;`? In the sense that when the on_restart features are not enabled, it is not them that should determine when the search is done.

**Comment by Dekker1** [comment]
Hi Sam,

This was indeed an oversight with the implementation of the feature. It shouldn't have any effect when it is not enabled. I generally run the MiniZinc test suite with new features for Chuffed to see whether they work correctly, but must have ran it wrong after adding these final flags to minimize the impact on the solver performance.

I'll fix the problem, do some more testing, and then push them back to the develop branch.

**Comment by Dekker1** [comment]
The current `develop` branch once again passes all tests in the MiniZinc test suite. Thanks for your contribution!
