### ISSUE TITLE
clang-tidy: Performance checks not actually enabled

### ISSUE THREAD

**Issue by waywardmonkeys** [chuffed/chuffed#171]
There's a typo in the config with `performace` instead of `performance`:

https://github.com/chuffed/chuffed/blob/60a0a1e342c1c3b7d45f7c9b9db36de4775973bb/.clang-tidy#L16

Unfortunately, correcting this turns up a lot of warnings (many of which so far seem to involve `BoolView`).

**Comment by Dekker1** [comment]
Thank you for pointing that out. I had been working on enabling some more clang-tidy check, so I'll add fixing this to my list
