### ISSUE TITLE
SAT encoding, SAT translation from Minizinc

### ISSUE THREAD

**Issue by niyozbek** [chuffed/chuffed#183]
Hi,
I was wondering, if anyone knows how chuffed is translating or encoding MiniZinc problem into SAT? Such as DIMACS.
Kind regards,
Niyozbek Obidov
Research Assistant at Swansea University

**Comment by Dekker1** [comment]
Chuffed doesn't directly translate the MiniZinc instance into SAT. It is a Lazy Clause Generation solver, which (essentially) means that it has external propagation, and encodes some logic of the constraints when conflicts are found. You can read more here: https://link.springer.com/content/pdf/10.1007/s10601-008-9064-x.pdf

If you are really just looking for a translation to the DIMACS format, then you can have a look at the Picat SAT solver. The MiniZinc team also has a prototype encoder to SAT, feel free to contact us if you want to try it.

**Comment by niyozbek** [comment]
@Dekker1  thanks! Can you please share with me "MiniZinc prototype encoder to SAT"?
I've emailed you as well!
