### ISSUE TITLE
Introduce Support for `indomain_random` in Solver Annotations

### ISSUE THREAD

**Issue by MatteoFasulo** [chuffed/chuffed#194]
## Description:
Hello,

I am writing to request help with introducing the support for `indomain_random` in solver annotations for the Chuffed solver.

### Issue:

Currently, the Chuffed solver does not support the `indomain_random` annotation. This limits the flexibility and potential performance of the solver in certain scenarios.

Thank you for your time and consideration.

**Comment by schutta** [comment]
I close this issue, because it is a duplicate of the issue #122 .
