### ISSUE TITLE
multithread support

### ISSUE THREAD

**Issue by zahednejad** [chuffed/chuffed#20]
Thanks for your efficient solver, i would really appreciate if anybody tell me how to increase the thread o Chuffed solver. In the configuration tab, as i increase the thread option, there is an error that says :" Unknown error while executing minizinc interpretor".

**Comment by Dekker1** [comment]
Chuffed currently does not support parallel/multithreaded search. The feature can be tracked in #66, but is unlikely to be resolved anytime soon because of limited developer availability
