### ISSUE TITLE
Multiple problems with conversion from "Cost-Regular" to "weighted-MDD"

### ISSUE THREAD

**Issue by Behrouz-Babaki** [chuffed/chuffed#23]
# Multiple problems with conversion from *Cost-Regular* to *weighted-MDD*

There are a few problems with the current implementation of the `wmdd_cost_regular` constraint:

### Array indices
When constructing the transitions (in [these lines](https://github.com/chuffed/chuffed/blob/ecb49672611cbe7850804fbe667f13f3115e7cef/chuffed/globals/mddglobals.cpp#L171-L172) of `mddglobals.cpp`), there is an index array that should change with the loop iterations, but is set to a fixed number:

```cpp
  for(int qi = 0; qi < q; qi++)
  {
    vec<int>& d_q(d[q]);
    vec<int>& w_q(w[q]);
```

This should change into:

```cpp
  for(int qi = 0; qi < q; qi++)
  {
    vec<int>& d_q(d[qi]);
    vec<int>& w_q(w[qi]);
```

### Initialization order
Right [after that](https://github.com/chuffed/chuffed/blob/ecb49672611cbe7850804fbe667f13f3115e7cef/chuffed/globals/mddglobals.cpp#L176), the transition structure (`WDFATrans`) is initialized in the wrong order:

```cpp
    WDFATrans t = { d_q[vi], w_q[vi] };
```

The correct initialization would be:

```cpp
    WDFATrans t = { w_q[vi], d_q[vi] };
```

### Initial state

The `wmdd_cost_regular` constraint [allows](https://github.com/chuffed/chuffed/blob/ecb49672611cbe7850804fbe667f13f3115e7cef/chuffed/globals/mddglobals.cpp#L164-L165) the user to specify the initil state. The conversion function `wdfa_to_layergraph` [does not](https://github.com/chuffed/chuffed/blob/ecb49672611cbe7850804fbe667f13f3115e7cef/chuffed/globals/mddglobals.cpp#L182) take this value as an argument, and [assumes](https://github.com/chuffed/chuffed/blob/ecb49672611cbe7850804fbe667f13f3115e7cef/chuffed/mdd/weighted_dfa.cpp#L217) that the initial state is always zero. 

### Offset

These [comments](https://github.com/chuffed/chuffed/blob/ecb49672611cbe7850804fbe667f13f3115e7cef/chuffed/globals/mddglobals.cpp#L159-L162) precede the definition of the `wmdd_cost_regular` function:

```cpp
// x: Vars | q: # states | s: alphabet size | d[state,symbol] -> state | q0: start state | f: accepts
// States range from 1..q (0 is reserved as dead)
// offset -> alphabet symbols are 1..s
//   (0..s-1 otherwise)
```

First, this function does not have an `offset` argument. Second, the assumption that states and alphabet start from one is violated in a few places. For example, [here](https://github.com/chuffed/chuffed/blob/ecb49672611cbe7850804fbe667f13f3115e7cef/chuffed/mdd/weighted_dfa.cpp#L184):

```cpp
  for(int ai = 0; ai < accepts.size(); ai++)
  {
    layers[curr][accepts[ai]] = EVLayerGraph::EVTrue;
  }
```

which should change into:

```cpp
  for(int ai = 0; ai < accepts.size(); ai++)
  {
    layers[curr][accepts[ai]-1] = EVLayerGraph::EVTrue;
  }
```

another example is in [these](https://github.com/chuffed/chuffed/blob/ecb49672611cbe7850804fbe667f13f3115e7cef/chuffed/mdd/weighted_dfa.cpp#L200-L211) lines:

```cpp
      for(int xi = 0; xi < dom; xi++)
      {
        // Compute the corresponding transition
        int tidx = soff + xi;
        const WDFATrans& trans(T[tidx]);
        EVLayerGraph::NodeID dest = layers[prev][trans.dest];
        if(dest != EVLayerGraph::EVFalse)
        {
          EVLayerGraph::EInfo edge = { xi, trans.weight, layers[prev][trans.dest] };
          edges.push(edge);
        }
      }
```
which needs these changes to work as expected:

```cpp
    EVLayerGraph::NodeID dest = layers[prev][trans.dest-1];
```

and 

```cpp
     EVLayerGraph::EInfo edge = { xi+1, trans.weight, layers[prev][trans.dest-1] };
```

I have implemented a fix that resolves these issues. I can submit a pull request, if that's okay.

**Comment by schutta** [comment]
Please, submit a pull request, so that we can review it.
