### ISSUE TITLE
Chuffed crashes due to bug in branching

### ISSUE THREAD

**Issue by the-kiel** [chuffed/chuffed#30]
Hi, 
there is a bug in chuffed which causes it to crash in some cases, for example in the following case: 

````
var -1..0: v;

solve :: int_search([v], input_order, indomain_reverse_split, complete) satisfy;
````

The problem comes from the branching in vars/int-var.c (and also vars/int-var-ll.c if a lazy literal is used), where the branching value is computed as x=(min+max)/2 (in this case, x=0).
Then, in vars/int-var.h it is tried to branch v>=x+1, which crashes in this case.

**Comment by schutta** [comment]
Should be fixed in the develop branch now.
