### ISSUE TITLE
Segmentation fault (MiniZinc 2.2.3)

### ISSUE THREAD

**Issue by matsc-at-sics-se** [chuffed/chuffed#37]
```
$ fzn-chuffed -v *.fzn
Segmentation fault (core dumped)
```
[oocsp1_racks_link_test.fzn.gz](https://github.com/chuffed/chuffed/files/2745952/oocsp1_racks_link_test.fzn.gz)

**Comment by Dekker1** [comment]
I've traced this bug to another mean usage of `dynamic_cast(this)` in the parser. A fix will be submitted shortly
