### ISSUE TITLE
Example where chuffed fails. Commit 45e778bf7e8be02887ba89c527828e672a877c2e Jan 17 2019

### ISSUE THREAD

**Issue by glebbelov** [chuffed/chuffed#40]
Fails after about half-hour on Debian 9.6 with MZN fe9a7640bf55760ad58beca9226505cadf1ebecb, see the model input.mzn on MZN Forum from 21.02.2019 https://groups.google.com/d/msg/minizinc/70PIE5zjG-Y/a56hJyPoBAAJ

$ minizinc -v -s --solver chuffed input.mzn
MiniZinc to FlatZinc converter, version 2.2.3
Copyright (C) 2014-2019 Monash University, NICTA, Data61
Parsing file(s) input.mzn' ...
processing file '/home/bg19/Documents/prj/minizinc/00/share/minizinc/std//stdlib.mzn'
processing file '/home/bg19/Documents/prj/minizinc/00/share/minizinc/std//builtins.mzn'
processing file '/home/bg19/Documents/prj/minizinc/00/share/minizinc/std//redefinitions-2.2.1.mzn'
processing file '/home/bg19/Documents/prj/minizinc/00/share/minizinc/std//redefinitions-2.1.1.mzn'
processing file '/home/bg19/Documents/prj/minizinc/00/share/minizinc/std//redefinitions-2.1.mzn'
processing file '/home/bg19/Documents/prj/minizinc/00/share/minizinc/std//redefinitions-2.0.2.mzn'
processing file '/home/bg19/Documents/prj/minizinc/00/share/minizinc/std//redefinitions-2.0.mzn'
processing file '/usr/local/share/chuffed/mznlib//redefinitions.mzn'
processing file '/home/bg19/Documents/prj/minizinc/00/share/minizinc/std//flatzinc_builtins.mzn'
processing file './input.mzn'
 done parsing (0.15 s)
Flattening ...
        CompilePass: Flatten with '/home/bg19/Documents/prj/minizinc/00/share/minizinc//' library ...
MIP domains ... done (0.35 s)
Optimizing ... done (0.38 s)
Converting to old FlatZinc ... done (0.51 s)
 done (0.51 s)
 done (0.66 s), max stack depth 25
Generated FlatZinc statistics:
Paths: 0
Variables: 15278 bool, 1208 int
Constraints: 9948 bool, 5797 int
    This is a minimization problem.
Maximum memory 55 Mbytes.
  Flattening done, 0.66 s
      % SOLVING PHASE
FZN solver plugin, compiled  Feb 19 2019  13:19:03
Using FZN solver /usr/local/bin/fzn-chuffed for solving, parameters: -s -v
=====ERROR=====
   Done (overall time 1256.97 s).

**Comment by Dekker1** [comment]
This problem is likely resolved with all recent crashes that have been resolved. I'm afraid that I didn't have time to test this exact case, so feel free to reopen this issue if it can still be found.
