### ISSUE TITLE
Feature request: priority search

### ISSUE THREAD

**Issue by Colelyman** [chuffed/chuffed#41]
First of all, thank you for your work on creating such an amazing solver! For my problem domain, I have found that Chuffed excels at finding many solutions and doing it quickly.

I have recently found this paper [Priority Search with MiniZinc](https://ozgurakgun.github.io/ModRef2017/files/ModRef2017_PrioritySearchWithMiniZinc.pdf) that would be helpful for our modelling. Essentially we would like to prioritize different parts of the objective function, and it seems like this would be a fairly straightforward way to implement that.

I'm not sure what the roadmap Chuffed development is, but if this could be implemented it would certainly help us. Also, any pointers/warnings would be appreciated in case we decide to implement it ourselves.

Thank you,
Cole

**Comment by schutta** [comment]
Priority search is already available in the release. Just include Chuffed's specific MiniZinc definitions in your MiniZinc model by
```
include "chuffed.mzn";
```
Have a look at [chuffed.mzn](https://github.com/chuffed/chuffed/blob/master/chuffed/flatzinc/mznlib/chuffed.mzn).

**Comment by Colelyman** [comment]
Thank you @schutta!

**Comment by Colelyman** [comment]
Before adding `priority_search` to my real model I have been trying to get it to work on the n-queens problem.

Here is the model that I have:
```
include "chuffed.mzn";
include "alldifferent.mzn";

int: n = 10;
array [1..n] of var 1..n: q;

constraint alldifferent(q);
constraint alldifferent([ q[i] + i | i in 1..n ]);
constraint alldifferent([ q[i] - i | i in 1..n ]);

solve :: priority_search(q, [input_order], smallest, complete) satisfy;

output [ if fix(q[j]) == i then "Q" else "." endif ++
         if j == n then "\n" else "" endif | i,j in 1..n]
```

It complies to FlatZinc just fine, but when it runs I get the message:

    % Error in search annotation: Unknown search annotation. Ignore search annotation!

I am on the current `origin/develop` branch, is there something I am missing in order to get `priority_search` to work? Or is this error unrelated to `priority_search`?

Thank you,
Cole
