### ISSUE TITLE
strange learnt nogood

### ISSUE THREAD

**Issue by matsc-at-sics-se** [chuffed/chuffed#45]
MiniZinc 2.3.0.
I ran a model instance with `--learnt-stats-nogood` and obtained the learnt nogood:

```
X_INTRODUCED_12645_<=479 >=12 X_INTRODUCED_12664_<=599 X_INTRODUCED_2433_<=0
```

What does that mean? What's `>=12` doing there?

**Comment by Dekker1** [comment]
This issue is rather old, and was never really picked up. Did you still have your example?

I'm wondering whether this might have been a variable introduced within Chuffed itself. This would then not have a name as such.

**Comment by matsc-at-sics-se** [comment]
Sorry, no, the example was lost.

**Comment by Dekker1** [comment]
Okay, then I'll close this issue for now. Feel free to open a new issue if this issue pops up again, and I'll be happy to further investigate
