### ISSUE TITLE
Compilation errors when compiling for parallel mode

### ISSUE THREAD

**Issue by broesdecat** [chuffed/chuffed#5]
Hi,

When compiling for parallel solving (with #define PARALLEL), I get the following compilation errors:
chuffed/parallel/master.cpp: In member function ‘void Master::initMPI()’:
chuffed/parallel/master.cpp:36:96: error: ‘ERROR’ was not declared in this scope
  if (so.num_threads > MAX_SLAVES) ERROR("Maximum number of slaves (%d) exceeded!\n", MAX_SLAVES);

chuffed/parallel/slave.cpp: In member function ‘void Slave::receiveLearnts()’:
chuffed/parallel/slave.cpp:222:38: error: ‘class SAT’ has no member named ‘level’
    if (sat.value(x) != l_True || sat.level[var(x)] != 0) {
                                      ^
chuffed/parallel/slave.cpp: In member function ‘void SAT::convertToSClause(Clause&)’:
chuffed/parallel/slave.cpp:248:31: error: ‘struct ChannelInfo’ has no member named ‘vid’
   int vid = c_info[var(c[i])].vid;
                               ^
chuffed/parallel/slave.cpp:251:43: error: ‘struct ChannelInfo’ has no member named ‘v’
    temp_sc->data[j++] = c_info[var(c[i])].v ^ sign(c[i]);
                                           ^
chuffed/parallel/slave.cpp: In member function ‘void SAT::addLearnt()’:
chuffed/parallel/slave.cpp:284:16: error: ‘level’ was not declared in this scope
   int hlevel = level[var(c[0])]; j = 0;
                ^
chuffed/parallel/slave.cpp:297:16: error: ‘level’ was not declared in this scope
   int hlevel = level[var(c[1])]; j = 1;
                ^

Best,
Broes

**Comment by Dekker1** [comment]
The parallel mode currently included in the Chuffed codebase is not supported (and likely incorrect). We will shortly remove it to avoid any confusion.
