### ISSUE TITLE
Segfault on CVRP instance

### ISSUE THREAD

**Issue by pwn1** [chuffed/chuffed#51]
Hi,

I built fzn-chuffed (current master branch) on MacOS X Catalina using the default clang compiler. 

The attached instance causes a seg fault. I have deleted hundreds of the constraints in an attempt to narrow down to a single propagator, however the crash seems to involve more than one constraint. Some of the constraints have a "% mark" comment on them, these are ones that I found to contribute to the seg fault (i.e. if I remove them then chuffed runs normally and finds a solution). The instance has not been reduced fully -- I thought you might have something that could do the reduction automatically since I have been doing it manually and it is very laborious.

[eil13.eprime-param.fzn.txt](https://github.com/chuffed/chuffed/files/4087031/eil13.eprime-param.fzn.txt)

Thanks,
Peter

**Comment by Dekker1** [comment]
This FlatZinc model now seems to correctly find a solution on the `develop` branch

**Comment by pwn1** [comment]
That's great, thanks Jip
