### ISSUE TITLE
Best solution so far is not output after interruption

### ISSUE THREAD

**Issue by cyderize** [chuffed/chuffed#54]
See minizinc/libminizinc#397.

I believe chuffed outputs the current best solution when its own `-t` timeout occurs, but it doesn't do this when interrupted (it handles this, but only gives statistics, not a solution).

Sometimes chuffed's own timeout takes much longer than expected (especially when there are a lot of solutions, which is potentially something else to investigate). MiniZinc then fallsback to killing chuffed, and then the unknown status is given.

**Comment by raphaelboudreault** [comment]
Statistics from Chuffed are not outputted when the timeout occurs, using MiniZinc 2.5.5 with option `-t`.

**Comment by cyderize** [comment]
Fixed in c3e86ee5c8fcc618ba3b4d0befae8c4692234440
