### ISSUE TITLE
How to Cite Your Tool?

### ISSUE THREAD

**Issue by hadipourh** [chuffed/chuffed#67]
Dear Chuffed developer team,

Hope you are fine. How to cite your tool if we are using it in our publications? 

Kind regards, 
Hosein

**Comment by Colelyman** [comment]
I'm not on the developer team, but I have used the following paper (and associate BibTeX entry) to cite Chuffed. If there is a better paper to cite, please let me know!

https://doi.org/10.1007/s10601-014-9163-9

```
@article{Chu_2014,
	doi = {10.1007/s10601-014-9163-9},
	year = 2014,
	month = {mar},
	publisher = {Springer Science and Business Media {LLC}},
	volume = {19},
	number = {4},
	pages = {434--462},
	author = {Geoffrey Chu and Maria Garcia de la Banda and Christopher Mears and Peter J. Stuckey},
	title = {Symmetries, almost symmetries, and lazy clause generation},
	journal = {Constraints}
}
```

**Comment by hadipourh** [comment]
Many thanks for considering my question.

**Comment by schutta** [comment]
We normally cite Geoffrey Chu's PhD thesis for the general tool, which is available at https://minerva-access.unimelb.edu.au/handle/11343/36679. 
```
@PHDTHESIS{Chu:11,
  author = {Chu, Geoffrey},
  title = {Improving Combinatorial Optimization},
  school = {The University of Melbourne},
  year = {2011},
  url = {http://hdl.handle.net/11343/36679}
}
```
Note that the different constraints were developed and implemented by others than Geoffrey Chu. If we use one of them then we will cite the related paper, too. Definitely, it would be good to have an overview about the different contributions and their relevant papers.
