### ISSUE TITLE
Unclear format of statistics output

### ISSUE THREAD

**Issue by HelgeS** [chuffed/chuffed#7]
Hallo,

I'm running chuffed via the minizinc interface for an optimization problem and include the '-s' option to obtain statistics:
$ mzn-chuffed <model.mzn> -s
Output: 200,21,865,3,0,0,4412,201,0.00,0.01

How is this string to be read?
I can identify the first value to be the optimization objective, but afterward, I have to start guessing.

Suggestions for improvement:
a) Maybe adapt to the format used by other solvers (e.g. gecode): 
> Runtime: x
> Solutions: y
> ...

or b) document the string format somewhere.

Thanks,
Helge

**Comment by schutta** [comment]
You get more sensitive information using the parameter --verbosity 2.

**Comment by HelgeS** [comment]
Great, thank you.

For future reference, it works like this:
$ mzn-chuffed <model.mzn> -s
```200,21,865,3,0,0,4412,201,0.00,0.01```

$ mzn-chuffed <model.mzn> -s --fzn-flags "--verbosity 2"

The output is similar to:
```
21 vars (0 no lits, 21 eager lits, 0 lazy lits)
3 propagators
0 conflicts
2301 nodes
4412 propagations
201 solutions
0.00 seconds init time
0.01 seconds opt time
0.01 seconds search time
0.00Mb base memory usage
0.00Mb trail memory usage
0.00Mb peak memory usage

865 SAT variables
0 orig bin clauses
0 orig tern clauses
0 orig long clauses (avg. len. 0.00)
0 learnt clauses (avg. len. 0.00)
165065 SAT propagations
0 back jumps
0 natural restarts
simplex = 0
refactors = 0
```
