### ISSUE TITLE
parser.tab.h confusion: build picks the bundled file over the built one

### ISSUE THREAD

**Issue by yurivict** [chuffed/chuffed#75]
First, the build failed:
```
fatal error: 'parser.tab.h' file not found
```
so I had to add ```-I${BUILD_WRKSRC}/chuffed/flatzinc/```

Then compiler failed to find YYEMPTY because ```chuffed/flatzinc/parser.tab.h``` was still picked. I had to delete it.

**Comment by Dekker1** [comment]
I think this problem has been resolved in more recent versions of the CMake setup. Otherwise, feel free to create a new issue
