### ISSUE TITLE
Manual of Chuffed

### ISSUE THREAD

**Issue by ruixinwang88** [chuffed/chuffed#8]
Hello,

I'm a Ph.D student at ENAC (Aeronautical University) in France, working
on cooperation between different solvers applied to Civil Aviation
combinatorial optimization problems.

I'm very interested in Chuffed as it has proven to be a very efficient
CP solver in nogood learning, particularly for a conflict resolution
problem I'm currently working on. In order to make a cooperation with
other algorithm possible, I'd like to know whether there is a manual for
the C++ API of Chuffed?

If not, what I'm trying to achieve is a communication with other
processes during the search, i.e. sending/receiving information on the
current state of the resolution, at regular intervals. Which part of the
C++ API code should I target?

**Comment by schutta** [comment]
Unfortunately, there is no manual. You should look at the function `Engine::search`  in `chuffed/core/engine.cpp`.

**Comment by ruixinwang88** [comment]
Thank you for your response.
