### ISSUE TITLE
On Windows, calling fzn-chuffed programmatically doesn't always have an output

### ISSUE THREAD

**Issue by dourouc05** [chuffed/chuffed#82]
Working on a Julia binding to Chuffed through its FlatZinc parser, I'm getting an awkward situation where, at random, fzn-chuffed does not output anything to stdout when called from Julia. Running again the exact same command usually yields the right output. I can quite reliably reproduce this by running the test suite from [Chuffed.jl](https://github.com/dourouc05/Chuffed.jl/).

It's likely that it's just a flushing issue when writing the results to stdout. I suppose that adding a call like [`std::cout << std::flush`](https://en.cppreference.com/w/cpp/io/manip/flush) at the end of `main` in `fzn-chuffed.cpp` should do the trick.

Related issues: https://github.com/chuffed/chuffed/issues/81, https://github.com/dourouc05/ConstraintProgrammingExtensions.jl/issues/24.

**Comment by schutta** [comment]
Can you please test your suppose solution will solve the issue, please?
