### ISSUE TITLE
Bad optimal solution reported (Cumulative constraint)

### ISSUE THREAD

**Issue by Samclou** [chuffed/chuffed#92]
Similarly to chuffed/chuffed#70, but by forcing the use of Chuffed's cumulative constraint in the attached model, Chuffed stops at 938 and reports it as optimal. If you set the upper bound to 930 instead of 1000, Chuffed finds a solution with cost 930 and says it is optimal as well. If the upper bound is still set to 1000 and the ttef_filt annotation is set to false instead, Chuffed also finds a solution with cost 930 and says it is optimal.

```
include "fzn_cumulative.mzn";
int:nrJobs=10;
int:nrRes=10;

set of int: J=1..nrJobs;
set of int: R=1..nrRes;

array[J,R] of int:taskUse = [|
   0, 1, 2, 3, 4, 5, 6, 7, 8, 9|
   0, 2, 4, 9, 3, 1, 6, 5, 7, 8|
   1, 0, 3, 2, 8, 5, 7, 6, 9, 4|
   1, 2, 0, 4, 6, 8, 7, 3, 9, 5|
   2, 0, 1, 5, 3, 4, 8, 7, 9, 6|
   2, 1, 5, 3, 8, 9, 0, 6, 4, 7|
   1, 0, 3, 2, 6, 5, 9, 8, 7, 4|
   2, 0, 1, 5, 4, 6, 8, 9, 7, 3|
   0, 1, 3, 5, 2, 9, 6, 7, 4, 8|
   1, 0, 2, 6, 8, 9, 5, 3, 4, 7 |];
   		
array[J,R] of int:taskDuration= [|
   29, 78,  9, 36, 49, 11, 62, 56, 44, 21|
   43, 90, 75, 11, 69, 28, 46, 46, 72, 30|
   91, 85, 39, 74, 90, 10, 12, 89, 45, 33|
   81, 95, 71, 99,  9, 52, 85, 98, 22, 43|
   14,  6, 22, 61, 26, 69, 21, 49, 72, 53|
   84,  2, 52, 95, 48, 72, 47, 65,  6, 25|
   46, 37, 61, 13, 32, 21, 32, 89, 30, 55|
   31, 86, 46, 74, 32, 88, 19, 48, 36, 79|
   76, 69, 76, 51, 85, 11, 40, 89, 26, 74|
   85, 13, 61,  7, 64, 76, 47, 52, 90, 45 |];
   								

int:ub = 1000;


array[J,R] of var 0..ub:start;
var 0..ub:objective;

constraint forall(j in J) 
  (objective >= start[j,nrRes]+taskDuration[j,nrRes]);
constraint forall(j in J, r in 1..nrRes-1)
 (start[j,r+1] >= start[j,r]+taskDuration[j,r]);
 constraint forall (r in R)
   (fzn_cumulative([start[j,k]|j in J, k in R where taskUse[j,k]+1=r],
                           [taskDuration[j,k]|j in J, k in R where taskUse[j,k]+1=r],
                           [1|j in J, k in R where taskUse[j,k]+1=r],1) :: tt_filt(true) :: ttef_check(true) :: ttef_filt(true)
   );
  
 solve minimize objective;
```

**Comment by schutta** [comment]
Thank you reporting the issue and providing more details and the cause in a private communication. I have fixed the issue with the commit 8677a08.

The issue occurred when there were remaining energy units left after lifting the start time variable of the to-be-propagated start time variable for generating a strongest explanation. However, these remaining energy units cannot be used for the lifting of other tasks and the resource capacity as it is implemented. To make usage of these units, one has to implement a specialised lifting procedure.
